module.exports = {
  compilerOptions: {
    target: 'ES2022',
    lib: ['ES2022'],
    module: 'ESNext',
    moduleResolution: 'bundler',
    allowImportingTsExtensions: false,
    resolveJsonModule: true,
    isolatedModules: true,
    noEmit: false,
    strict: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noFallthroughCasesInSwitch: true,
    noUncheckedSideEffectImports: true,
    allowJs: false,
    skipLibCheck: true,
    forceConsistentCasingInFileNames: true,
    declaration: true,
    declarationMap: true,
    sourceMap: true,
    composite: true,
    incremental: true,
    paths: {
      '@orbytech/sdk': ['../../packages/sdk/src'],
      '@orbytech/ui': ['../../packages/ui/src'],
    },
  },
  include: ['src/**/*'],
  exclude: ['node_modules', 'dist', 'build'],
};
